# Generated by Django 5.1.4 on 2025-01-20 04:52

import attendance_app.validators
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('team_name', models.CharField(max_length=15, null=True, validators=[attendance_app.validators.validate_no_special_characters])),
                ('grade', models.CharField(max_length=15, null=True, validators=[attendance_app.validators.validate_no_special_characters])),
                ('profile_pic', models.ImageField(default='default_profile_pic.jpg', upload_to='profile_pics')),
                ('intro', models.CharField(blank=True, max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_type', models.CharField(choices=[('ABSENCE', '결근'), ('ANNUAL_LEAVE', '연차'), ('LATE', '지각'), ('EARLY_LEAVE', '조퇴'), ('BUSINESS_TRIP', '출장')], default=None, max_length=20, verbose_name='근태 유형')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='시작 시점')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='종료 시점')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='신청 사유')),
                ('tot_time', models.FloatField(default=0.0)),
                ('attachment1', models.FileField(blank=True, null=True, upload_to='attendance_pics', verbose_name='첨부파일')),
                ('attachment2', models.FileField(blank=True, null=True, upload_to='attendance_pics', verbose_name='첨부파일')),
                ('attachment3', models.FileField(blank=True, null=True, upload_to='attendance_pics', verbose_name='첨부파일')),
                ('team_leader_approver', models.CharField(blank=True, max_length=50, null=True, verbose_name='팀장 승인자')),
                ('team_leader_approval_date', models.DateTimeField(blank=True, null=True, verbose_name='팀장 승인일자')),
                ('final_approver', models.CharField(blank=True, max_length=50, null=True, verbose_name='최종 승인자')),
                ('final_approval_date', models.DateTimeField(blank=True, null=True, verbose_name='최종 승인일자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_requests', to=settings.AUTH_USER_MODEL, verbose_name='신청자')),
            ],
            options={
                'verbose_name': '근태 신청서',
                'verbose_name_plural': '근태 신청서',
                'ordering': ['-start_date'],
            },
        ),
    ]
